---
# group_vars/galaxyFS-builder.yml
#
#   Variables used when building galaxyFS

#-- Galaxy configs
cm_setup_galaxy: yes
gvl_genomespace_server: "genomespace.genome.edu.au"
# Just the default values from the underlying role but required for post_tasks
galaxy_user_name: galaxy
galaxyFS_base_dir: /mnt/galaxy
indicesFS_base_dir: /mnt/galaxyIndices
galaxy_server_dir: "{{ galaxyFS_base_dir }}/galaxy-app"

galaxy_vcs: git
galaxy_changeset_id: gvl
galaxy_venv_dir: "{{ galaxy_server_dir }}/.venv"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini"

cm_install_tools: yes
shed_tool_list_file: roles/gvl.filesystem/files/scripts/shed_tool_list.yaml.gvl
cm_install_data: no
dbkeys_list_file: files/dbkeys_list.yaml.cloud

galaxy_genome_data_path: /mnt/galaxyIndices/genomes
galaxy_config_dir: "{{ galaxy_server_dir }}/config"
galaxy_mutable_data_dir: "{{ galaxyFS_base_dir }}"
galaxy_mutable_config_dir: "{{ galaxyFS_base_dir }}/var"
galaxy_shed_tools_dir: "{{ galaxyFS_base_dir }}/shed_tools"

galaxy_db_log: /tmp/pSQL.log

galaxy_manage_trackster: yes
len_file_path: "{{ galaxyFS_base_dir }}/configuration_data/len"
bedtools_version: 2.20.1

gvl_fs_name: "GVL FileSystem"
gvl_fs_flavour: default
gvl_fs_build_date: "{{ ansible_date_time.iso8601 }}"
gvl_version: "4.00"
gvl_fs_version: "{{ gvl_version }}"
gvl_galaxy_brand: "GVL {{ gvl_version }}"

galaxy_config:
  "server:main":
    port: "{{ galaxy_webserver_port }}"
    host: 127.0.0.1
  "app:main":
    filter-with: proxy-prefix
    database_connection: postgresql://{{ galaxy_user_name }}@localhost:{{ galaxy_db_port }}/galaxy
    install_database_connection: sqlite:///{{ galaxy_mutable_config_dir }}/galaxy_install_db.sqlite?isolation_level=IMMEDIATE
    database_engine_option_pool_size: 20
    database_engine_option_max_overflow: 50
    database_engine_option_server_side_cursors: True
    database_engine_option_strategy: threadlocal
    genome_data_path: "{{ galaxy_genome_data_path }}"
    rsync_url: rsync://scofield.bx.psu.edu/indexes
    static_enabled: True
    nginx_x_accel_redirect_base: /_x_accel_redirect
    nginx_upload_store: "{{ galaxyFS_base_dir }}/upload_store"
    nginx_upload_path: /_upload
    library_import_dir: "{{ galaxyFS_base_dir }}/tmp/library_import_dir"
    allow_library_path_paste: True
    allow_user_dataset_purge: True
    enable_openid: True
    enable_unique_workflow_defaults: True
    ftp_upload_dir: "{{ galaxyFS_base_dir }}/tmp/ftp"
    track_jobs_in_database: True
    enable_job_recovery: True
    set_metadata_externally: True
    retry_metadata_internally: True
    outputs_to_working_directory: False
    cleanup_job: onsuccess
    cluster_job_queue_workers: 3
    use_pbkdf2: False
    allow_user_deletion: True

    file_path: "{{ galaxyFS_base_dir }}/files"
    tool_dependency_dir: "{{ galaxyFS_base_dir }}/tools"
    len_file_path: "{{ len_file_path }}"
    shed_tool_data_path: "{{ galaxy_server_dir }}/tool-data/dm"
    galaxy_data_manager_data_path: /mnt/galaxy/userIndices

    tool_config_file: "{{ galaxy_config_dir }}/tool_conf.xml,{{ galaxy_config_dir }}/shed_tool_conf_cloud.xml,{{ galaxy_shed_tool_conf_file }}"
    tool_data_table_config_path: "{{ galaxy_config_dir }}/tool_data_table_conf.xml"
    datatypes_config_file: "{{ galaxy_config_dir }}/datatypes_conf.xml"
    migrated_tools_config: "{{ galaxy_mutable_config_dir }}/migrated_tools_conf.xml"
    shed_tool_data_table_config: "{{ galaxy_mutable_config_dir }}/shed_tool_data_table_conf.xml"
    tool_sheds_config_file: "{{ galaxy_mutable_config_dir }}/tool_sheds_conf.xml.sample"
    builds_file_path: "{{ galaxy_config_dir }}/builds.txt"

    brand: "{{ gvl_galaxy_brand }}"
    support_url: https://genome.edu.au/wiki/GVL_Help
    ucsc_display_sites: gvlmain,test,archaea,ucla
    static_dir: "{{ galaxy_server_dir }}/static/"
    static_images_dir: "{{ galaxy_server_dir }}/static/images"
    static_favicon_dir: "{{ galaxy_server_dir }}/static/favicon.ico"
    static_scripts_dir: "{{ galaxy_server_dir }}/static/scripts/"
    static_robots_txt: "{{ galaxy_server_dir }}/static/robots.txt"
    allow_user_deletion: True
    expose_dataset_path: True
    visualization_plugins_directory: config/plugins/visualizations

  "filter:gzip":
    use: egg:Paste#gzip
  "filter:proxy-prefix":
    use: egg:PasteDeploy#prefix
    prefix: /galaxy

galaxy_mutable_configs:
  - src: "{{ galaxy_server_dir }}/config/shed_tool_conf.xml.sample"
    dest: "{{ galaxy_shed_tool_conf_file }}"
  - src: "{{ galaxy_server_dir }}/config/migrated_tools_conf.xml.sample"
    dest: "{{ galaxy_config['app:main']['migrated_tools_config'] if galaxy_config is defined and 'app:main' in galaxy_config and 'migrated_tools_config' in galaxy_config['app:main'] else galaxy_config_default['app:main']['migrated_tools_config'] }}"
  - src: "{{ galaxy_server_dir }}/config/shed_data_manager_conf.xml.sample"
    dest: "{{ galaxy_config['app:main']['shed_data_manager_config_file'] if galaxy_config is defined and 'app:main' in galaxy_config and 'shed_data_manager_config_file' in galaxy_config['app:main'] else galaxy_config_default['app:main']['shed_data_manager_config_file'] }}"
  - src: "{{ galaxy_server_dir }}/config/shed_tool_data_table_conf.xml.sample"
    dest: "{{ galaxy_config['app:main']['shed_tool_data_table_config'] if galaxy_config is defined and 'app:main' in galaxy_config and 'shed_tool_data_table_config' in galaxy_config['app:main'] else galaxy_config_default['app:main']['shed_tool_data_table_config'] }}"
  - src: "{{ galaxy_server_dir }}/config/datatypes_conf.xml.sample"
    dest: "{{ galaxy_config['app:main']['datatypes_config_file'] if galaxy_config is defined and 'app:main' in galaxy_config and 'datatypes_config_file' in galaxy_config['app:main'] else galaxy_config_default['app:main']['datatypes_config_file'] }}"
  - src: "{{ galaxy_server_dir }}/config/tool_data_table_conf.xml.sample"
    dest: "{{ galaxy_config['app:main']['tool_data_table_config_path'] }}"
  - src: "{{ galaxy_server_dir }}/config/tool_conf.xml.sample"
    dest: "{{ galaxy_config_dir }}/tool_conf.xml"
  - src: "{{ galaxy_server_dir }}/tool-data/shared/ucsc/builds.txt.sample"
    dest: "{{ galaxy_config['app:main']['builds_file_path'] }}"
  - src: "{{ galaxy_server_dir }}/config/tool_sheds_conf.xml.sample"
    dest: "{{ galaxy_config['app:main']['tool_sheds_config_file'] }}"

#-- Pulsar configs
pulsar_server_dir: "{{ galaxyFS_base_dir }}/pulsar"
pulsar_dependencies_dir: "{{ galaxyFS_base_dir }}/tools"
pulsar_drmaa_library_path: /usr/lib/slurm-drmaa/lib/libdrmaa.so
pulsar_host: "0.0.0.0"
pulsar_optional_dependencies:
  - pyOpenSSL
  - pycurl==7.19.3.1 # https://github.com/pycurl/pycurl/issues/201
  - uwsgi
  - drmaa
  - requests
  - poster
  - psutil

# gvl setup details
galaxy_git_repo: https://github.com/gvlproject/galaxy
galaxy_changeset_id: gvl_{{ gvl_version }}
galaxy_webserver_port: 8080
galaxy_admin_user_password: "TODO-GenerateRandomOrDeleteBootstrapUser"

# gvl archive upload details
gvl_create_archive: False
# cloudman_bucket_name: cm-ng-dev
gvl_fs_archive_name: "gvl-galaxyfs-{{ gvl_version }}.tar.gz"
gvl_fs_archive_path: /tmp/galaxy_archive
OS_AUTH_URL: https://keystone.rc.nectar.org.au:5000/v2.0/
# OS_TENANT_ID:
# OS_TENANT_NAME:
# OS_USERNAME:
# OS_PASSWORD:

cmg_extra_files:
  - src: roles/gvl.filesystem/files/galaxy-app
    dest: "{{ galaxyFS_base_dir }}"